# 배열 다루기 루틴

In [0]:
import numpy as np

Q1. x가 10x10x3의 다차원 배열일때, x의 두번째 차원이 150인 2차원 배열이 되도록 reshape하세요.

In [0]:
x = np.ones([10, 10, 3])


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

Q2. x가 [[1, 2, 3], [4, 5, 6]]일 때, [1 4 2 5 3 6]로 변환하세요.

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

Q3. x가 [[1, 2, 3], [4, 5, 6]]일 때, flatten한 후 5번째 원소를 가져오세요.

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out = x.flatten()

out[?]

5

Q4. 

x= <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
y = <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>


x와 y를 연결해서
<br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]]
를 만드세요


In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])



array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q5. 

x= <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
y = <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>


x와 y를 연결해서
<br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]
를 만드세요

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])




array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q6. x가 [0, 1, 2]일 때, [0, 0, 1, 1, 2, 2]를 생성하세요.

In [0]:
x = np.array([0, 1, 2])



array([0, 0, 1, 1, 2, 2])

Q7. x가 [0, 0, 0, 1, 2, 3, 0, 2, 1, 0]일 때,<br/>
앞, 뒤의 0을 제거하세요.

In [0]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))



array([1, 2, 3, 0, 2, 1])